# 环境配置
environment:
  name: unitreego2  # 环境名称
  robot_path: envs/unitree_go2/scene.xml   # 机器狗模型地址
  render_mode: human  # 渲染模式
  max_episode_steps: 500  # 每个episode最大步数
  seed: 42  # 环境随机种子

# agent网络结构
agent_network:
  policy_hdim: [128, 128, 64]
  v_hdim: [128, 128, 64]
  hdim: [128, 128, 64]
  activation: tanh  # 激活函数

# 算法参数
algorithm_ppo:
  name: PPO  # 算法名称
  learning_rate: 0.0003  # 学习率
  gamma: 0.99  # 折扣因子
  clip_epsilon: 0.2
  entropy_coef: 0.001
  original_coef: 0.1

algorithm_sac:
  name: SAC  # 算法名称
  learning_rate: 0.0003  # 学习率
  gamma: 0.99  # 折扣因子
  buffer_size: 10000

# 训练参数
training:
  render: False
  max_episodes: 100000 # 总训练步数
  max_steps: 300
  batch_size: 64
  log_interval: 10  # 日志记录间隔
  save_interval: 100  # 模型保存间隔
  eval_interval: 50  # 评估间隔
  n_eval_episodes: 10  # 每次评估使用的episode数
  output_dir: models
  pre_model_path:
#  pre_model_path: models/unitree_ppo_10w_old.pth

# 回放缓冲区
replay_buffer:
  buffer_size: 3000
  batch_size: 128

# 设备设置
device:
  use_gpu: true
  device_id: 0